import { useState, useEffect, createContext, useContext, useMemo, useRef, useCallback } from "react";
import { Users, FolderKanban, Receipt, ChevronLeft, ChevronRight, Bell, Search, TrendingUp, AlertTriangle, Clock, CheckCircle, XCircle, ArrowRight, Calendar, Building2, FileWarning, Phone, Mail, MapPin, CircleDollarSign, Menu, X, Info, Plus, Save, UserCircle, ShieldCheck, LogOut, MessageSquare, Hash, Banknote, FileText, Target, UserPlus, NotebookPen, Sun, Moon, Monitor, Tablet, Smartphone, User, Pencil, MessageCircle, Upload, FileSpreadsheet, ShieldAlert, GripVertical, ClipboardList, Flag } from "lucide-react";
import { PieChart, Pie, Cell, ResponsiveContainer, BarChart, Bar, XAxis, YAxis, Tooltip, CartesianGrid } from "recharts";
import googleSheetsService from './api/googleSheetsService';

const ThemeCtx = createContext();
const useTh = () => useContext(ThemeCtx);

const TEAM=["Christopher","Linssi","José"];
const KCOLS=[{id:"Pendiente",color:"#c4a265",bg:"bg-[#c4a265]/10"},{id:"En Proceso",color:"#3b82f6",bg:"bg-blue-500/10"},{id:"Terminado",color:"#22c55e",bg:"bg-emerald-500/10"},{id:"Atrasado",color:"#ef4444",bg:"bg-red-500/10"}];
const PRIOS=["Baja","Media","Alta","Crítica"];
const prioClr=p=>({"Baja":"bg-slate-500/15 text-slate-500","Media":"bg-sky-500/15 text-sky-600 dark:text-sky-400","Alta":"bg-amber-500/15 text-amber-600 dark:text-amber-400","Crítica":"bg-red-500/15 text-red-500"}[p]||"bg-slate-500/15 text-slate-500");

const RM={admin:{l:"Administrador",d:"Acceso completo"},crm:{l:"Gestión CRM",d:"Clientes y bitácora"},cobros:{l:"Cartera / Cobros",d:"Facturación y cobros"}};
const $=n=>new Intl.NumberFormat("es-PA",{style:"currency",currency:"USD",minimumFractionDigits:0,maximumFractionDigits:0}).format(n);
const fd=d=>{if(!d)return"—";try{return new Date(d+"T12:00:00").toLocaleDateString("es-PA",{day:"2-digit",month:"short",year:"numeric"});}catch{return d;}};
const bg=e=>({"Cliente Activo":"bg-emerald-500/15 text-emerald-600 dark:text-emerald-400 border-emerald-500/20",Prospecto:"bg-sky-500/15 text-sky-600 dark:text-sky-400 border-sky-500/20",Cotizando:"bg-violet-500/15 text-violet-600 dark:text-violet-400 border-violet-500/20","En Litigio/Moroso":"bg-red-500/15 text-red-600 dark:text-red-400 border-red-500/20",Ejecución:"bg-emerald-500/15 text-emerald-600 dark:text-emerald-400 border-emerald-500/20",Suspendido:"bg-red-500/15 text-red-600 dark:text-red-400 border-red-500/20",Entregado:"bg-sky-500/15 text-sky-600 dark:text-sky-400 border-sky-500/20","En Planificación":"bg-indigo-500/15 text-indigo-600 dark:text-indigo-400 border-indigo-500/20",Pagado:"bg-emerald-500/15 text-emerald-600 dark:text-emerald-400 border-emerald-500/20",Pendiente:"bg-amber-500/15 text-amber-600 dark:text-amber-400 border-amber-500/20","En Disputa Técnica":"bg-orange-500/15 text-orange-600 dark:text-orange-300 border-orange-500/20","Pago Parcial":"bg-yellow-500/15 text-yellow-600 dark:text-yellow-400 border-yellow-500/20"}[e]||"bg-slate-500/15 text-slate-500 border-slate-500/20")+" border";
const compSt=(c,prjs,facs)=>{if(c.estado_relacion==="Prospecto"&&!prjs.some(p=>p.id_cliente===c.id_cliente))return"Prospecto";const cp=prjs.filter(p=>p.id_cliente===c.id_cliente);if(cp.some(p=>p.estado_obra==="Cotizando"))return"Cotizando";const ff=facs||[];const hasMora=ff.some(f=>{const pr=cp.find(p=>p.id_proyecto===f.id_proyecto);return pr&&f.dias_mora>0&&f.estado_cobro!=="Pagado";});if(hasMora||c.estado_relacion==="En Litigio/Moroso")return"En Litigio/Moroso";if(cp.some(p=>["Ejecución","Entregado","En Planificación"].includes(p.estado_obra)))return"Cliente Activo";return c.estado_relacion;};
const gC=(b,a,prjs)=>b.id_cliente?a.find(c=>c.id_cliente===b.id_cliente):b.id_proyecto?a.find(c=>c.id_cliente===(prjs||[]).find(p=>p.id_proyecto===b.id_proyecto)?.id_cliente):null;
const gP=(b,prjs)=>b.id_proyecto?(prjs||[]).find(p=>p.id_proyecto===b.id_proyecto):null;
const iM={Llamada:Phone,Email:Mail,"Visita a Obra":MapPin,WhatsApp:MessageSquare};

function Toast({ts,rm}){return<div className="fixed bottom-4 right-4 z-[100] flex flex-col gap-2">{ts.map(t=><div key={t.id} style={{animation:"sU .3s ease-out"}} className={`flex items-center gap-3 px-4 py-3 rounded-xl shadow-2xl border text-sm ${t.y==="success"?"bg-emerald-50 dark:bg-emerald-950/90 border-emerald-300 dark:border-emerald-500/30 text-emerald-700 dark:text-emerald-200":"bg-red-50 dark:bg-red-950/90 border-red-300 dark:border-red-500/30 text-red-700 dark:text-red-200"}`}>{t.y==="success"?<CheckCircle size={16}/>:<XCircle size={16}/>}{t.m}<button onClick={()=>rm(t.id)} className="ml-2 opacity-60 hover:opacity-100"><X size={14}/></button></div>)}</div>;}
function KPI({title,value,sub,icon:I,ac="brand"}){const cls={brand:"bg-[#c4a265]/10 text-[#c4a265]",emerald:"bg-emerald-500/10 text-emerald-500",red:"bg-red-500/10 text-red-500",amber:"bg-amber-500/10 text-amber-500",sky:"bg-sky-500/10 text-sky-500",orange:"bg-orange-500/10 text-orange-500",violet:"bg-violet-500/10 text-violet-500"};const[b2,tx]=(cls[ac]||"").split(" ");return<div className="cd p-4 lg:p-5 hover:shadow-lg transition-all"><div className="flex items-start justify-between mb-2"><span className="text-[10px] font-semibold tracking-wider uppercase text-slate-500">{title}</span><div className={`p-2 rounded-xl ${b2}`}><I size={17} className={tx}/></div></div><div className="text-2xl lg:text-3xl font-bold text-slate-900 dark:text-white">{value}</div>{sub&&<div className="text-[11px] text-slate-500 mt-1">{sub}</div>}</div>;}
function Mod({open,close,title,children,w}){if(!open)return null;return<div className="fixed inset-0 z-[80] flex items-center justify-center p-4" onClick={close}><div className="absolute inset-0 bg-black/50 backdrop-blur-sm"/><div className={`relative bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-700/50 rounded-2xl shadow-2xl w-full ${w?"max-w-2xl":"max-w-lg"} max-h-[90vh] overflow-y-auto`} onClick={e=>e.stopPropagation()}><div className="flex items-center justify-between px-5 py-4 border-b border-slate-200 dark:border-slate-700/40 sticky top-0 bg-white dark:bg-slate-900 z-10 rounded-t-2xl"><h2 className="text-base font-bold text-slate-900 dark:text-white">{title}</h2><button onClick={close} className="p-1 rounded-lg hover:bg-slate-100 dark:hover:bg-slate-800 text-slate-400"><X size={18}/></button></div><div className="p-5">{children}</div></div></div>;}
function Inp({l,v,ch,type="text",ph,opts,ta,req}){const b="w-full bg-slate-50 dark:bg-slate-800/60 border border-slate-200 dark:border-slate-700/40 rounded-xl px-3 py-2.5 text-sm text-slate-900 dark:text-slate-200 placeholder-slate-400 outline-none focus:border-[#c4a265]/50 focus:ring-1 focus:ring-[#c4a265]/20 transition-all";return<div><label className="block text-xs font-semibold text-slate-500 mb-1.5">{l}{req&&<span className="text-red-400 ml-0.5">*</span>}</label>{opts?<select value={v} onChange={e=>ch(e.target.value)} className={b}>{opts.map(o=>typeof o==="object"?<option key={o.v} value={o.v}>{o.l}</option>:<option key={o} value={o}>{o}</option>)}</select>:ta?<textarea value={v} onChange={e=>ch(e.target.value)} className={`${b} h-24 resize-none`} placeholder={ph}/>:<input type={type} value={v} onChange={e=>ch(e.target.value)} className={b} placeholder={ph}/>}</div>;}

function RoleSel({setRole}){return<div className="min-h-screen flex items-center justify-center p-4 bg-[#f8f6f1] dark:bg-[#0b1120]"><div className="w-full max-w-md"><div className="flex flex-col items-center mb-8"><div className="w-16 h-16 rounded-2xl bg-gradient-to-br from-[#c4a265] to-[#8b6f3a] flex items-center justify-center mb-3 shadow-lg"><span className="text-2xl font-black text-white">TL</span></div><div className="text-xl font-bold text-slate-800 dark:text-white">TorresLeón</div><div className="text-[11px] text-[#c4a265] tracking-[.25em] uppercase font-semibold">Ingeniería & Gestión</div></div><div className="cd p-6 shadow-xl"><h2 className="text-sm font-semibold text-slate-700 dark:text-slate-300 mb-1">Selecciona tu perfil</h2><p className="text-xs text-slate-500 mb-5">El acceso depende de tu rol.</p><div className="space-y-3">{Object.entries(RM).map(([k,v])=><button key={k} onClick={()=>setRole(k)} className="w-full flex items-center gap-4 p-4 rounded-xl border border-slate-200 dark:border-slate-700/30 bg-slate-50 dark:bg-slate-800/30 hover:border-[#c4a265]/40 hover:bg-[#c4a265]/5 transition-all group"><div className="w-10 h-10 rounded-xl bg-[#c4a265]/10 flex items-center justify-center"><ShieldCheck size={20} className="text-[#c4a265]"/></div><div className="text-left flex-1"><div className="text-sm font-semibold text-slate-800 dark:text-white">{v.l}</div><div className="text-[11px] text-slate-500">{v.d}</div></div><ArrowRight size={16} className="text-slate-400 group-hover:text-[#c4a265]"/></button>)}</div></div></div></div>;}

function Sidebar({col,setCol,view,setView,mob,setMob,role}){const nav=useMemo(()=>[{id:"dash-crm",l:"Dashboard CRM",i:Users,r:["admin","crm"]},{id:"dash-cobros",l:"Dashboard Cobros",i:Receipt,r:["admin","cobros"]},{id:"clientes",l:"Clientes",i:UserCircle,r:["admin","crm"]},{id:"proyectos",l:"Proyectos",i:FolderKanban,r:["admin","crm","cobros"]},{id:"cobros",l:"Cartera",i:Banknote,r:["admin","cobros"]},{id:"tareas",l:"Tareas",i:ClipboardList,r:["admin","crm","cobros"]},{id:"bitacora",l:"Bitácora CRM",i:NotebookPen,r:["admin","crm"]}].filter(n=>n.r.includes(role)),[role]);
  const inner=<div className="flex flex-col h-full"><div className={`flex items-center gap-3 px-4 py-4 border-b border-slate-200 dark:border-slate-700/40 ${col&&!mob?"justify-center":""}`}><div className="w-9 h-9 rounded-xl bg-gradient-to-br from-[#c4a265] to-[#8b6f3a] flex items-center justify-center shrink-0 shadow"><span className="text-xs font-black text-white">TL</span></div>{(!col||mob)&&<div><div className="text-sm font-bold text-slate-800 dark:text-white leading-tight">TorresLeón</div><div className="text-[9px] text-[#c4a265] tracking-[.15em] uppercase font-semibold">Ingeniería & Gestión</div></div>}</div><nav className="flex-1 py-3 px-2 space-y-0.5">{nav.map(n=>{const a=view===n.id;return<button key={n.id} onClick={()=>{setView(n.id);setMob(false);}} className={`w-full flex items-center gap-3 px-3 py-2.5 rounded-xl text-sm font-medium transition-all ${a?"bg-[#c4a265]/10 text-[#c4a265]":"text-slate-500 hover:text-slate-800 dark:hover:text-slate-200 hover:bg-slate-100 dark:hover:bg-slate-700/30"} ${col&&!mob?"justify-center":""}`}><n.i size={18}/>{(!col||mob)&&<span>{n.l}</span>}</button>;})}</nav>{(!col||mob)&&<div className="mx-3 mb-3 p-3 rounded-xl bg-slate-50 dark:bg-slate-800/60 border border-slate-200 dark:border-slate-700/20"><div className="flex items-center gap-2"><div className="w-2 h-2 rounded-full bg-emerald-500"/><span className="text-[11px] font-semibold text-slate-600 dark:text-slate-300">{RM[role].l}</span></div><div className="text-[10px] text-slate-400 mt-0.5">Google Sheets <span className="text-emerald-500">conectado</span></div></div>}<button onClick={()=>{setCol(!col);setMob(false);}} className="hidden lg:flex items-center justify-center py-3 border-t border-slate-200 dark:border-slate-700/40 text-slate-400 hover:text-slate-600 dark:hover:text-slate-300">{col?<ChevronRight size={16}/>:<ChevronLeft size={16}/>}</button></div>;
  return<><aside className={`hidden lg:flex flex-col fixed left-0 top-0 h-full bg-white/95 dark:bg-slate-900/95 backdrop-blur-xl border-r border-slate-200 dark:border-slate-700/40 z-40 transition-all duration-300 ${col?"w-[68px]":"w-[230px]"}`}>{inner}</aside>{mob&&<div className="lg:hidden fixed inset-0 bg-black/50 z-40" onClick={()=>setMob(false)}/>}<aside className={`lg:hidden fixed left-0 top-0 h-full w-[260px] bg-white dark:bg-slate-900 border-r border-slate-200 dark:border-slate-700/40 z-50 transition-transform duration-300 ${mob?"translate-x-0":"-translate-x-full"}`}><button onClick={()=>setMob(false)} className="absolute top-4 right-4 text-slate-400"><X size={20}/></button>{inner}</aside></>;
}

function Topbar({setMob,role,setRole,vm,setVm}){const{dark,toggle}=useTh();return<header className="fixed top-0 right-0 left-0 z-30 h-14 flex items-center justify-between px-3 lg:px-5 bg-white/80 dark:bg-slate-900/80 backdrop-blur-xl border-b border-slate-200 dark:border-slate-700/30"><div className="flex items-center gap-2"><button onClick={()=>setMob(true)} className="lg:hidden p-2 -ml-1 text-slate-400"><Menu size={20}/></button><div className="hidden md:flex items-center gap-2 bg-slate-50 dark:bg-slate-800/60 rounded-xl px-3 py-2 border border-slate-200 dark:border-slate-700/30 w-[200px]"><Search size={14} className="text-slate-400"/><input className="bg-transparent text-sm text-slate-700 dark:text-slate-300 placeholder-slate-400 outline-none w-full" placeholder="Buscar..."/></div></div><div className="flex items-center gap-1"><div className="hidden sm:flex items-center gap-0.5 bg-slate-100 dark:bg-slate-800/60 rounded-lg p-0.5 border border-slate-200 dark:border-slate-700/30">{[[" mobile",Smartphone],["tablet",Tablet],["desktop",Monitor]].map(([id,I])=><button key={id} onClick={()=>setVm(id.trim())} className={`p-1.5 rounded-md transition-all ${vm===id.trim()?"bg-white dark:bg-slate-700 shadow-sm text-[#c4a265]":"text-slate-400"}`}><I size={14}/></button>)}</div><button onClick={toggle} className="p-2 rounded-xl hover:bg-slate-100 dark:hover:bg-slate-800/60 text-slate-400">{dark?<Sun size={16}/>:<Moon size={16}/>}</button><button className="relative p-2 rounded-xl hover:bg-slate-100 dark:hover:bg-slate-800/60 text-slate-400"><Bell size={16}/><span className="absolute -top-0.5 -right-0.5 w-4 h-4 rounded-full bg-red-500 text-[9px] font-bold text-white flex items-center justify-center">5</span></button><div className="flex items-center gap-2 pl-2 border-l border-slate-200 dark:border-slate-700/40"><div className="w-8 h-8 rounded-full bg-gradient-to-br from-[#c4a265] to-[#8b6f3a] flex items-center justify-center text-xs font-bold text-white">AV</div><div className="hidden md:block"><div className="text-xs font-semibold text-slate-700 dark:text-slate-200">Álvaro V.</div><div className="text-[10px] text-slate-400">{RM[role].l}</div></div></div><button onClick={()=>setRole(null)} className="p-2 rounded-xl hover:bg-slate-100 dark:hover:bg-slate-800/60 text-slate-400"><LogOut size={15}/></button></div></header>;}

const ttS={background:"var(--tt-bg)",border:"1px solid var(--tt-border)",borderRadius:12,fontSize:12,color:"var(--tt-text)"};

function DashCRM({cls,crm,prjs}){const a=cls.filter(c=>c.estado_relacion==="Cliente Activo").length,m=cls.filter(c=>c.estado_relacion==="En Litigio/Moroso").length,p=cls.filter(c=>c.estado_relacion==="Prospecto").length,co=cls.filter(c=>c.estado_relacion==="Cotizando").length;const pie=[{name:"Activos",value:a,color:"#22c55e"},{name:"Morosos",value:m,color:"#ef4444"},{name:"Prospectos",value:p,color:"#38bdf8"},{name:"Cotizando",value:co,color:"#a78bfa"}];const rec=[...crm].sort((a,b)=>b.fecha_contacto.localeCompare(a.fecha_contacto)).slice(0,6);
  return<div className="space-y-6"><div><h1 className="text-xl lg:text-2xl font-bold text-slate-900 dark:text-white">Dashboard CRM</h1><p className="text-sm text-slate-500 mt-0.5">Gestión de relaciones — {new Date().toLocaleDateString("es-PA",{day:"numeric",month:"long",year:"numeric"})}</p></div><div className="grid grid-cols-2 xl:grid-cols-4 gap-3"><KPI title="Clientes Activos" value={a} sub={`de ${cls.length}`} icon={Users} ac="emerald"/><KPI title="En Litigio" value={m} icon={AlertTriangle} ac="red"/><KPI title="Prospectos" value={p} icon={Target} ac="sky"/><KPI title="Cotizando" value={co} icon={FileText} ac="violet"/></div>
    <div className="grid grid-cols-1 lg:grid-cols-3 gap-4"><div className="cd p-5"><h3 className="text-sm font-semibold text-slate-700 dark:text-slate-300 mb-3">Distribución</h3><ResponsiveContainer width="100%" height={170}><PieChart><Pie data={pie} cx="50%" cy="50%" innerRadius={42} outerRadius={68} paddingAngle={3} dataKey="value" stroke="none">{pie.map((e,i)=><Cell key={i} fill={e.color}/>)}</Pie><Tooltip contentStyle={ttS}/></PieChart></ResponsiveContainer><div className="flex flex-wrap gap-3 mt-2 justify-center">{pie.map(d=><div key={d.name} className="flex items-center gap-1.5"><div className="w-2.5 h-2.5 rounded-full" style={{background:d.color}}/><span className="text-[11px] text-slate-500">{d.name} ({d.value})</span></div>)}</div></div>
      <div className="cd p-5"><h3 className="text-sm font-semibold text-slate-700 dark:text-slate-300 mb-3">Tipo</h3><ResponsiveContainer width="100%" height={170}><BarChart data={[{n:"B2B",c:cls.filter(c=>c.tipo_cliente==="B2B").length},{n:"B2C",c:cls.filter(c=>c.tipo_cliente==="B2C").length}]} barSize={36}><CartesianGrid strokeDasharray="3 3" stroke="var(--grid)"/><XAxis dataKey="n" tick={{fill:"var(--ax)",fontSize:12}}/><YAxis tick={{fill:"var(--ax)",fontSize:11}}/><Tooltip contentStyle={ttS}/><Bar dataKey="c" fill="#c4a265" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></div>
      <div className="cd p-5"><h3 className="text-sm font-semibold text-slate-700 dark:text-slate-300 mb-3">En Riesgo</h3><div className="space-y-2">{cls.filter(c=>c.estado_relacion==="En Litigio/Moroso").slice(0,5).map(c=><div key={c.id_cliente} className="flex items-center gap-3 p-2.5 rounded-xl bg-red-50 dark:bg-red-500/5 border border-red-200 dark:border-red-500/10"><div className="w-8 h-8 rounded-lg bg-red-500/15 flex items-center justify-center text-[11px] font-bold text-red-500">{c.razon_social_nombre[0]}</div><div className="min-w-0"><div className="text-xs font-semibold text-slate-700 dark:text-slate-200 truncate">{c.razon_social_nombre}</div><div className="text-[10px] text-slate-500">{c.contacto_principal}</div></div></div>)}</div></div></div>
    <div className="cd p-5"><h3 className="text-sm font-semibold text-slate-700 dark:text-slate-300 mb-4">Actividad Reciente</h3><div className="space-y-2.5">{rec.map(b=>{const I=iM[b.tipo_contacto]||Info;const pry=gP(b,prjs);const cli=gC(b,cls,prjs);const co2=!b.id_proyecto&&b.id_cliente;return<div key={b.id_interaccion} className="flex gap-3 p-3 rounded-xl bg-slate-50 dark:bg-slate-900/30 border border-slate-100 dark:border-slate-700/15"><div className="w-9 h-9 rounded-lg bg-[#c4a265]/10 flex items-center justify-center shrink-0"><I size={15} className="text-[#c4a265]"/></div><div className="min-w-0 flex-1"><div className="flex items-center gap-2 flex-wrap"><span className="text-xs font-semibold text-slate-700 dark:text-slate-200">{b.tipo_contacto}</span><span className="text-[11px] text-slate-500">{fd(b.fecha_contacto)}</span>{co2&&<span className="text-[10px] px-1.5 py-0.5 rounded bg-violet-500/10 text-violet-500 border border-violet-500/15 inline-flex items-center gap-0.5"><User size={8}/>Cliente</span>}{pry&&<span className="text-[11px] text-[#c4a265]/70">{pry.nombre_proyecto}</span>}</div><p className="text-xs text-slate-500 mt-0.5 line-clamp-2">{b.notas_acuerdos}</p>{b.promesa_pago&&<div className="mt-1 text-[10px] px-2 py-0.5 rounded-full bg-amber-500/10 text-amber-600 dark:text-amber-400 border border-amber-500/15 inline-flex items-center gap-1"><Calendar size={9}/>{fd(b.promesa_pago)}</div>}</div></div>;})}</div></div></div>;}

function DashCob({cls,prjs,facs}){const pe=facs.filter(f=>f.estado_cobro==="Pendiente"),di=facs.filter(f=>f.estado_cobro==="En Disputa Técnica"),pa=facs.filter(f=>f.estado_cobro==="Pago Parcial");const tc=facs.filter(f=>f.estado_cobro!=="Pagado").reduce((s,f)=>s+f.monto_facturado,0),tm=facs.filter(f=>f.dias_mora>0).reduce((s,f)=>s+f.monto_facturado,0),td=di.reduce((s,f)=>s+f.monto_facturado,0);const ur=[...facs].filter(f=>f.estado_cobro!=="Pagado"&&f.dias_mora>0).sort((a,b)=>b.dias_mora-a.dias_mora);const pd=[{name:"Pendiente",value:pe.reduce((s,f)=>s+f.monto_facturado,0),color:"#f59e0b"},{name:"Disputa",value:td,color:"#f97316"},{name:"Parcial",value:pa.reduce((s,f)=>s+f.monto_facturado,0),color:"#eab308"}];
  return<div className="space-y-6"><div><h1 className="text-xl lg:text-2xl font-bold text-slate-900 dark:text-white">Dashboard de Cobros</h1><p className="text-sm text-slate-500">Control de cartera</p></div><div className="grid grid-cols-2 xl:grid-cols-4 gap-3"><KPI title="Cartera" value={$(tc)} sub={`${facs.filter(f=>f.estado_cobro!=="Pagado").length} facturas`} icon={CircleDollarSign} ac="brand"/><KPI title="En Mora" value={$(tm)} sub={`${facs.filter(f=>f.dias_mora>0).length} vencidas`} icon={AlertTriangle} ac="red"/><KPI title="Disputa" value={$(td)} sub={`${di.length}`} icon={FileWarning} ac="orange"/><KPI title="Pendiente" value={$(pe.reduce((s,f)=>s+f.monto_facturado,0))} sub={`${pe.length}`} icon={Clock} ac="amber"/></div>
    <div className="grid grid-cols-1 lg:grid-cols-5 gap-4"><div className="lg:col-span-2 cd p-5"><h3 className="text-sm font-semibold text-slate-700 dark:text-slate-300 mb-3">Composición</h3><ResponsiveContainer width="100%" height={190}><PieChart><Pie data={pd} cx="50%" cy="50%" innerRadius={48} outerRadius={75} paddingAngle={3} dataKey="value" stroke="none">{pd.map((e,i)=><Cell key={i} fill={e.color}/>)}</Pie><Tooltip formatter={v=>$(v)} contentStyle={ttS}/></PieChart></ResponsiveContainer><div className="flex flex-wrap gap-3 mt-2 justify-center">{pd.map(d=><div key={d.name} className="flex items-center gap-1.5"><div className="w-2.5 h-2.5 rounded-full" style={{background:d.color}}/><span className="text-[11px] text-slate-500">{d.name}</span></div>)}</div></div>
      <div className="lg:col-span-3 cd p-5"><h3 className="text-sm font-semibold text-slate-700 dark:text-slate-300 mb-3">Facturas con Mora</h3><div className="space-y-2">{ur.slice(0,5).map(f=>{const pr=prjs.find(p=>p.id_proyecto===f.id_proyecto);const cl=pr?cls.find(c=>c.id_cliente===pr.id_cliente):null;return<div key={f.id_factura} className="flex items-center gap-3 p-3 rounded-xl bg-slate-50 dark:bg-slate-900/40 border border-slate-100 dark:border-slate-700/20"><div className={`w-10 h-10 rounded-xl flex items-center justify-center shrink-0 ${f.dias_mora>60?"bg-red-500/15":"bg-amber-500/15"}`}><Clock size={16} className={f.dias_mora>60?"text-red-500":"text-amber-500"}/></div><div className="flex-1 min-w-0"><div className="text-xs font-semibold text-slate-700 dark:text-slate-200 truncate">{f.id_factura} — {cl?.razon_social_nombre||"—"}</div><div className="text-[11px] text-slate-500 truncate">{f.hitos_concepto}</div></div><div className="text-right shrink-0"><div className="text-sm font-bold text-slate-900 dark:text-white">{$(f.monto_facturado)}</div><div className={`text-[10px] font-semibold ${f.dias_mora>60?"text-red-500":"text-amber-500"}`}>{f.dias_mora}d</div></div></div>;})}</div></div></div></div>;}

function ClV({cls,setCls,toast,crm,setCrm,prjs,setView,setSelC,facs}){const[se,sSe]=useState("");const[fe,sFe]=useState("Todos");const[sf,sSf]=useState(false);const[ec,sEc]=useState(null);const[sb,sSb]=useState(null);
  const clsC=cls.map(c=>({...c,_st:compSt(c,prjs)}));
  // New client form
  const em={tipo_cliente:"B2B",razon_social_nombre:"",ruc_cedula:"",contacto_principal:"",telefono_whatsapp:"+507 ",email_facturacion:"",estado_relacion:"Prospecto",prospectado_por:"",seguimiento_por:"",comentarios:""};const[fm,sFm]=useState(em);const u=(k,v)=>sFm(p=>({...p,[k]:v}));
  const sv=()=>{if(!fm.razon_social_nombre||!fm.ruc_cedula){toast("Completa campos obligatorios","error");return;}setCls(p=>[...p,{...fm,id_cliente:`CLI-${String(p.length+1).padStart(3,"0")}`}]);toast("Cliente creado");sFm(em);sSf(false);};
  // Edit client form
  const[ef,sEf]=useState(null);
  const openEdit=(c)=>{sEf({...c});sEc(c.id_cliente);};
  const saveEdit=()=>{if(!ef)return;setCls(p=>p.map(c=>c.id_cliente===ec?{...ef}:c));toast("Cliente actualizado");sEc(null);sEf(null);};
  const ue=(k,v)=>sEf(p=>({...p,[k]:v}));
  // Inline bitácora form
  const[bf,sBf]=useState({tc:"Llamada",fc:new Date().toISOString().slice(0,10),n:"",pp:""});
  const saveBit=()=>{if(!bf.n){toast("Agrega una nota","error");return;}setCrm(p=>[{id_interaccion:`INT-${String(p.length+1).padStart(3,"0")}`,id_proyecto:"",id_cliente:sb,fecha_contacto:bf.fc,tipo_contacto:bf.tc,notas_acuerdos:bf.n,promesa_pago:bf.pp},...p]);toast("Interacción registrada");sBf({tc:"Llamada",fc:new Date().toISOString().slice(0,10),n:"",pp:""});sSb(null);};
  const fl=clsC.filter(c=>(c.razon_social_nombre+c.ruc_cedula+c.contacto_principal).toLowerCase().includes(se.toLowerCase())&&(fe==="Todos"||c._st===fe));
  const isPorC=(s)=>s==="Prospecto"||s==="Cotizando";
  const bitCli=sb?crm.filter(b=>b.id_cliente===sb):[];
  const sbCli=sb?cls.find(c=>c.id_cliente===sb):null;
  return<div className="space-y-5"><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3"><div><h1 className="text-xl lg:text-2xl font-bold text-slate-900 dark:text-white">Clientes</h1><p className="text-sm text-slate-500">{cls.length} registrados</p></div><button onClick={()=>sSf(true)} className="flex items-center gap-2 px-4 py-2.5 rounded-xl bg-[#c4a265]/10 text-[#c4a265] border border-[#c4a265]/20 text-sm font-semibold"><UserPlus size={16}/>Nuevo</button></div>
    <div className="flex flex-col sm:flex-row gap-3"><div className="flex-1 flex items-center gap-2 bg-white dark:bg-slate-800/60 rounded-xl px-3 py-2.5 border border-slate-200 dark:border-slate-700/30"><Search size={15} className="text-slate-400"/><input value={se} onChange={e=>sSe(e.target.value)} className="bg-transparent text-sm text-slate-700 dark:text-slate-300 placeholder-slate-400 outline-none w-full" placeholder="Buscar..."/></div><div className="flex gap-1.5 flex-wrap">{["Todos","Prospecto","Cotizando","Cliente Activo","En Litigio/Moroso"].map(e=><button key={e} onClick={()=>sFe(e)} className={`px-2.5 py-2 rounded-xl text-[11px] font-semibold whitespace-nowrap ${fe===e?"bg-[#c4a265]/10 text-[#c4a265] border border-[#c4a265]/20":"bg-white dark:bg-slate-800/40 text-slate-500 border border-slate-200 dark:border-slate-700/30"}`}>{e}</button>)}</div></div>
    {/* Mobile cards */}
    <div className="lg:hidden space-y-2">{fl.map(c=>{const cp=prjs.filter(p=>p.id_cliente===c.id_cliente);return<div key={c.id_cliente} onClick={()=>{setView("c360");setSelC(c.id_cliente);}} className="cd p-4 cursor-pointer hover:border-[#c4a265]/30 transition-all"><div className="flex items-start justify-between mb-1"><div className="min-w-0 flex-1"><div className="text-sm font-semibold text-slate-800 dark:text-white truncate">{c.razon_social_nombre}</div><div className="text-[11px] text-slate-500">{c.contacto_principal}</div></div><div className="flex items-center gap-1.5 shrink-0 ml-2"><span className={`text-[9px] px-2 py-0.5 rounded-full font-semibold ${bg(c._st)}`}>{c._st}</span></div></div><div className="flex items-center gap-3 mt-1"><span className="text-[11px] text-slate-500">{c.ruc_cedula}</span><span className="text-[10px] px-2 py-0.5 rounded-full bg-slate-100 dark:bg-slate-700/40 text-slate-500">{cp.length} proy.</span></div></div>})}</div>
    {/* Desktop table */}
    <div className="hidden lg:block cd overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-left"><thead><tr className="border-b border-slate-200 dark:border-slate-700/30">{["Empresa","RUC","Tipo","Contacto","Proyectos","Estado",""].map(h=><th key={h} className="px-4 py-3 text-[10px] font-semibold uppercase text-slate-400">{h}</th>)}</tr></thead><tbody>{fl.map(c=>{const cp=prjs.filter(p=>p.id_cliente===c.id_cliente);return<tr key={c.id_cliente} onClick={()=>{setView("c360");setSelC(c.id_cliente);}} className="border-b border-slate-100 dark:border-slate-700/15 hover:bg-slate-50 dark:hover:bg-slate-800/40 cursor-pointer"><td className="px-4 py-3"><div className="text-sm font-semibold text-slate-800 dark:text-slate-200">{c.razon_social_nombre}</div>{c.prospectado_por&&<div className="text-[10px] text-sky-500 mt-0.5">Prospectado: {c.prospectado_por}{c.seguimiento_por?` • Seg: ${c.seguimiento_por}`:""}</div>}<div className="text-[10px] text-slate-400 mt-0.5">{c.telefono_whatsapp} • {c.email_facturacion}</div></td><td className="px-4 py-3 text-xs text-slate-500 font-mono">{c.ruc_cedula}</td><td className="px-4 py-3"><span className={`text-[10px] px-2 py-0.5 rounded-full font-semibold ${c.tipo_cliente==="B2B"?"bg-[#c4a265]/10 text-[#c4a265] border border-[#c4a265]/15":"bg-violet-500/10 text-violet-500 border border-violet-500/15"}`}>{c.tipo_cliente}</span></td><td className="px-4 py-3 text-xs text-slate-600 dark:text-slate-300">{c.contacto_principal}</td><td className="px-4 py-3 text-center"><span className={`text-xs font-bold ${cp.length>0?"text-[#c4a265]":"text-slate-400"}`}>{cp.length}</span></td><td className="px-4 py-3"><span className={`text-[10px] px-2 py-1 rounded-full font-semibold ${bg(c._st)}`}>{c._st}</span></td><td className="px-4 py-2" onClick={e=>e.stopPropagation()}><div className="flex gap-1"><button onClick={()=>openEdit(c)} className="p-1.5 rounded-lg hover:bg-slate-100 dark:hover:bg-slate-700 text-slate-400 hover:text-[#c4a265]" title="Editar"><Pencil size={13}/></button></div></td></tr>})}</tbody></table></div></div>
    {/* NEW CLIENT MODAL */}
    <Mod open={sf} close={()=>sSf(false)} title="Nuevo Cliente" w><div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><Inp l="Razón Social / Nombre" v={fm.razon_social_nombre} ch={v=>u("razon_social_nombre",v)} ph="Constructora ABC" req/><Inp l="RUC / Cédula" v={fm.ruc_cedula} ch={v=>u("ruc_cedula",v)} ph="155698-1-12345 DV 12" req/><Inp l="Tipo" v={fm.tipo_cliente} ch={v=>u("tipo_cliente",v)} opts={["B2B","B2C"]}/><Inp l="Contacto" v={fm.contacto_principal} ch={v=>u("contacto_principal",v)} ph="Nombre"/><Inp l="Teléfono" v={fm.telefono_whatsapp} ch={v=>u("telefono_whatsapp",v)} ph="+507 6XXX-XXXX"/><Inp l="Email" v={fm.email_facturacion} ch={v=>u("email_facturacion",v)} type="email" ph="correo@empresa.com"/><div className="sm:col-span-2"><Inp l="Estado" v={fm.estado_relacion} ch={v=>u("estado_relacion",v)} opts={["Prospecto","Cotizando","Cliente Activo","En Litigio/Moroso"]}/></div>{isPorC(fm.estado_relacion)&&<><Inp l="Prospectado por" v={fm.prospectado_por} ch={v=>u("prospectado_por",v)} opts={["","...seleccionar",...TEAM]}/><Inp l="Seguimiento por" v={fm.seguimiento_por} ch={v=>u("seguimiento_por",v)} opts={["","...seleccionar",...TEAM]}/></>}<div className="sm:col-span-2"><Inp l="Comentarios" v={fm.comentarios} ch={v=>u("comentarios",v)} ta ph="Notas internas sobre este cliente..."/></div></div><div className="flex justify-end gap-3 mt-6 pt-4 border-t border-slate-200 dark:border-slate-700/30"><button onClick={()=>sSf(false)} className="px-4 py-2.5 rounded-xl text-sm text-slate-500">Cancelar</button><button onClick={sv} className="flex items-center gap-2 px-5 py-2.5 rounded-xl bg-[#c4a265] hover:bg-[#b8956a] text-white text-sm font-semibold"><Save size={15}/>Guardar</button></div></Mod>
    {/* EDIT CLIENT MODAL */}
    <Mod open={!!ec} close={()=>{sEc(null);sEf(null);}} title="Modificar Cliente" w>{ef&&<><div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><Inp l="Razón Social / Nombre" v={ef.razon_social_nombre} ch={v=>ue("razon_social_nombre",v)} req/><Inp l="RUC / Cédula" v={ef.ruc_cedula} ch={v=>ue("ruc_cedula",v)} req/><Inp l="Tipo" v={ef.tipo_cliente} ch={v=>ue("tipo_cliente",v)} opts={["B2B","B2C"]}/><Inp l="Contacto" v={ef.contacto_principal} ch={v=>ue("contacto_principal",v)}/><Inp l="Teléfono" v={ef.telefono_whatsapp} ch={v=>ue("telefono_whatsapp",v)}/><Inp l="Email" v={ef.email_facturacion} ch={v=>ue("email_facturacion",v)} type="email"/><div className="sm:col-span-2"><Inp l="Estado de Relación" v={ef.estado_relacion} ch={v=>ue("estado_relacion",v)} opts={["Prospecto","Cotizando","Cliente Activo","En Litigio/Moroso"]}/></div>{isPorC(ef.estado_relacion)&&<><Inp l="Prospectado por" v={ef.prospectado_por||""} ch={v=>ue("prospectado_por",v)} opts={["","...seleccionar",...TEAM]}/><Inp l="Seguimiento por" v={ef.seguimiento_por||""} ch={v=>ue("seguimiento_por",v)} opts={["","...seleccionar",...TEAM]}/></>}<div className="sm:col-span-2"><Inp l="Comentarios" v={ef.comentarios||""} ch={v=>ue("comentarios",v)} ta ph="Notas internas sobre este cliente..."/></div></div><div className="flex justify-end gap-3 mt-6 pt-4 border-t border-slate-200 dark:border-slate-700/30"><button onClick={()=>{sEc(null);sEf(null);}} className="px-4 py-2.5 rounded-xl text-sm text-slate-500">Cancelar</button><button onClick={saveEdit} className="flex items-center gap-2 px-5 py-2.5 rounded-xl bg-[#c4a265] hover:bg-[#b8956a] text-white text-sm font-semibold"><Save size={15}/>Guardar Cambios</button></div></>}</Mod>
    {/* INLINE BITÁCORA MODAL */}
    <Mod open={!!sb} close={()=>sSb(null)} title={`Bitácora — ${sbCli?.razon_social_nombre||""}`} w>
      {sbCli&&<div className="mb-4 p-3 rounded-xl bg-slate-50 dark:bg-slate-800/60 border border-slate-200 dark:border-slate-700/20"><div className="flex items-center gap-2"><span className={`text-[10px] px-2 py-0.5 rounded-full font-semibold ${bg(sbCli.estado_relacion)}`}>{sbCli.estado_relacion}</span><span className="text-xs text-slate-500">{sbCli.contacto_principal}</span><span className="text-xs text-slate-400">{sbCli.telefono_whatsapp}</span></div></div>}
      <div className="mb-4 p-4 rounded-xl border border-dashed border-[#c4a265]/30 bg-[#c4a265]/5"><h4 className="text-xs font-semibold text-[#c4a265] mb-3 flex items-center gap-1.5"><Plus size={13}/>Nueva interacción</h4><div className="grid grid-cols-1 sm:grid-cols-2 gap-3"><Inp l="Tipo" v={bf.tc} ch={v=>sBf(p=>({...p,tc:v}))} opts={["Llamada","Email","Visita a Obra","WhatsApp"]}/><Inp l="Fecha" v={bf.fc} ch={v=>sBf(p=>({...p,fc:v}))} type="date"/><Inp l="Promesa Pago" v={bf.pp} ch={v=>sBf(p=>({...p,pp:v}))} type="date"/><div/><div className="sm:col-span-2"><Inp l="Notas" v={bf.n} ch={v=>sBf(p=>({...p,n:v}))} ta ph="Describe la interacción..." req/></div></div><div className="flex justify-end mt-3"><button onClick={saveBit} className="flex items-center gap-2 px-4 py-2 rounded-xl bg-[#c4a265] hover:bg-[#b8956a] text-white text-sm font-semibold"><Save size={14}/>Registrar</button></div></div>
      <h4 className="text-xs font-semibold text-slate-500 mb-2">Historial ({bitCli.length})</h4>
      {bitCli.length===0?<div className="text-center py-8 text-slate-400 text-sm">Sin interacciones registradas</div>:<div className="space-y-2 max-h-[300px] overflow-y-auto">{[...bitCli].sort((a,b)=>b.fecha_contacto.localeCompare(a.fecha_contacto)).map(b=>{const I=iM[b.tipo_contacto]||Info;return<div key={b.id_interaccion} className="flex gap-3 p-3 rounded-xl bg-slate-50 dark:bg-slate-900/30 border border-slate-100 dark:border-slate-700/15"><div className="w-8 h-8 rounded-lg bg-[#c4a265]/10 flex items-center justify-center shrink-0"><I size={14} className="text-[#c4a265]"/></div><div className="min-w-0"><div className="flex items-center gap-2"><span className="text-[11px] font-semibold text-slate-700 dark:text-slate-200">{b.tipo_contacto}</span><span className="text-[10px] text-slate-500">{fd(b.fecha_contacto)}</span></div><p className="text-xs text-slate-500 mt-0.5">{b.notas_acuerdos}</p>{b.promesa_pago&&<div className="mt-1 text-[10px] px-2 py-0.5 rounded-full bg-amber-500/10 text-amber-600 dark:text-amber-400 border border-amber-500/15 inline-flex items-center gap-1"><Calendar size={9}/>{fd(b.promesa_pago)}</div>}</div></div>;})}</div>}
    </Mod></div>;}

function PrV({cls,setCls,setView,setSP,prjs,setPrjs,toast,facs}){const[se,sSe]=useState("");const[fe,sFe]=useState("Todos");const[sf,sSf]=useState(false);const[nc,sNc]=useState(false);
  const estados=["Todos","Cotizando","Ejecución","En Planificación","Suspendido","Entregado"];
  const fl=prjs.filter(p=>p.nombre_proyecto.toLowerCase().includes(se.toLowerCase())&&(fe==="Todos"||p.estado_obra===fe));
  const emP={clientMode:"existing",id_cliente:"",nombre_proyecto:"",presupuesto_aprobado:"",fecha_inicio:new Date().toISOString().slice(0,10),project_manager:""};
  const emC={tipo_cliente:"B2B",razon_social_nombre:"",ruc_cedula:"",contacto_principal:"",telefono_whatsapp:"+507 ",email_facturacion:"",prospectado_por:"",seguimiento_por:""};
  const[pf,sPf]=useState(emP);const[cf,sCf]=useState(emC);const up=(k,v)=>sPf(p=>({...p,[k]:v}));const uc=(k,v)=>sCf(p=>({...p,[k]:v}));
  const savePrj=()=>{if(!pf.nombre_proyecto){toast("Nombre del proyecto requerido","error");return;}let cid=pf.id_cliente;if(pf.clientMode==="new"){if(!cf.razon_social_nombre||!cf.ruc_cedula){toast("Completa datos del cliente","error");return;}cid=`CLI-${String(cls.length+1).padStart(3,"0")}`;setCls(p=>[...p,{id_cliente:cid,...cf,estado_relacion:"Cotizando",comentarios:""}]);}if(!cid){toast("Selecciona o crea un cliente","error");return;}setPrjs(p=>[...p,{id_proyecto:`PRJ-${String(p.length+1).padStart(3,"0")}`,id_cliente:cid,nombre_proyecto:pf.nombre_proyecto,presupuesto_aprobado:Number(pf.presupuesto_aprobado)||0,fecha_inicio:pf.fecha_inicio,estado_obra:"Cotizando",project_manager:pf.project_manager}]);toast("Proyecto creado en Cotizando");sPf(emP);sCf(emC);sSf(false);sNc(false);};
  return<div className="space-y-5"><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3"><div><h1 className="text-xl lg:text-2xl font-bold text-slate-900 dark:text-white">Proyectos</h1><p className="text-sm text-slate-500">{prjs.length} en gestión</p></div><button onClick={()=>sSf(true)} className="flex items-center gap-2 px-4 py-2.5 rounded-xl bg-[#c4a265]/10 text-[#c4a265] border border-[#c4a265]/20 text-sm font-semibold"><Plus size={16}/>Nuevo Proyecto</button></div>
    <div className="flex flex-col sm:flex-row gap-3"><div className="flex-1 flex items-center gap-2 bg-white dark:bg-slate-800/60 rounded-xl px-3 py-2.5 border border-slate-200 dark:border-slate-700/30"><Search size={15} className="text-slate-400"/><input value={se} onChange={e=>sSe(e.target.value)} className="bg-transparent text-sm text-slate-700 dark:text-slate-300 placeholder-slate-400 outline-none w-full" placeholder="Buscar proyecto..."/></div><div className="flex gap-1.5 flex-wrap">{estados.map(e=><button key={e} onClick={()=>sFe(e)} className={`px-2.5 py-2 rounded-xl text-[11px] font-semibold whitespace-nowrap ${fe===e?"bg-[#c4a265]/10 text-[#c4a265] border border-[#c4a265]/20":"bg-white dark:bg-slate-800/40 text-slate-500 border border-slate-200 dark:border-slate-700/30"}`}>{e}</button>)}</div></div>
    {fl.length===0?<div className="text-center py-16 text-slate-400"><FolderKanban size={40} className="mx-auto mb-3 opacity-30"/><p className="text-sm">No se encontraron proyectos.</p></div>:<div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">{fl.map(p=>{const cl=cls.find(c=>c.id_cliente===p.id_cliente);const fs=facs.filter(f=>f.id_proyecto===p.id_proyecto);const ft=fs.reduce((s,f)=>s+f.monto_facturado,0);const pc=p.presupuesto_aprobado>0?Math.round(ft/p.presupuesto_aprobado*100):0;return<div key={p.id_proyecto} onClick={()=>{setSP(p.id_proyecto);setView("p360");}} className="cd p-5 hover:border-[#c4a265]/30 cursor-pointer group"><div className="flex items-start justify-between mb-2"><div className="min-w-0 flex-1"><div className="text-sm font-bold text-slate-800 dark:text-white group-hover:text-[#c4a265] truncate">{p.nombre_proyecto}</div><div className="text-[11px] text-slate-500 mt-0.5">{cl?.razon_social_nombre||p.id_cliente}</div></div><span className={`text-[9px] px-2 py-0.5 rounded-full font-semibold shrink-0 ml-2 ${bg(p.estado_obra)}`}>{p.estado_obra}</span></div><div className="text-[11px] text-slate-500 mb-3">PM: {p.project_manager}</div><div className="mb-3"><div className="flex justify-between text-[11px] mb-1"><span className="text-slate-500">Facturado</span><span className="font-semibold text-slate-800 dark:text-white">{pc}%</span></div><div className="h-2 rounded-full bg-slate-200 dark:bg-slate-700/50 overflow-hidden"><div className={`h-full rounded-full ${pc>=70?"bg-emerald-500":pc>=40?"bg-[#c4a265]":"bg-amber-500"}`} style={{width:`${Math.min(pc,100)}%`}}/></div></div><div className="grid grid-cols-2 gap-2 pt-3 border-t border-slate-200 dark:border-slate-700/20"><div><div className="text-[10px] text-slate-400">Presupuesto</div><div className="text-xs font-semibold text-slate-700 dark:text-slate-200">{$(p.presupuesto_aprobado)}</div></div><div><div className="text-[10px] text-slate-400">Facturado</div><div className="text-xs font-semibold text-[#c4a265]">{$(ft)}</div></div></div></div>;})}</div>}
    <Mod open={sf} close={()=>{sSf(false);sNc(false);}} title="Nuevo Proyecto" w>
      <div className="mb-4"><label className="block text-xs font-semibold text-slate-500 mb-2">Cliente</label><div className="flex gap-2"><button onClick={()=>{up("clientMode","existing");sNc(false);}} className={`flex-1 flex items-center justify-center gap-2 p-3 rounded-xl border text-sm font-semibold ${pf.clientMode==="existing"?"bg-[#c4a265]/10 text-[#c4a265] border-[#c4a265]/30":"bg-slate-50 dark:bg-slate-800/40 text-slate-500 border-slate-200 dark:border-slate-700/30"}`}><Users size={15}/>Existente</button><button onClick={()=>{up("clientMode","new");sNc(true);}} className={`flex-1 flex items-center justify-center gap-2 p-3 rounded-xl border text-sm font-semibold ${pf.clientMode==="new"?"bg-violet-500/10 text-violet-600 dark:text-violet-400 border-violet-500/30":"bg-slate-50 dark:bg-slate-800/40 text-slate-500 border-slate-200 dark:border-slate-700/30"}`}><UserPlus size={15}/>Crear Nuevo</button></div></div>
      {pf.clientMode==="existing"&&<div className="mb-4"><Inp l="Seleccionar Cliente" v={pf.id_cliente} ch={v=>up("id_cliente",v)} opts={[{v:"",l:"— Seleccionar —"},...cls.map(c=>({v:c.id_cliente,l:`${c.razon_social_nombre} (${c.estado_relacion})`}))]}/></div>}
      {nc&&<div className="mb-4 p-4 rounded-xl border border-dashed border-violet-500/30 bg-violet-500/5"><h4 className="text-xs font-semibold text-violet-500 mb-3 flex items-center gap-1.5"><UserPlus size={13}/>Nuevo cliente (se creará en Cotizando)</h4><div className="grid grid-cols-1 sm:grid-cols-2 gap-3"><Inp l="Razón Social / Nombre" v={cf.razon_social_nombre} ch={v=>uc("razon_social_nombre",v)} ph="Nombre o empresa" req/><Inp l="RUC / Cédula" v={cf.ruc_cedula} ch={v=>uc("ruc_cedula",v)} ph="155698-1-12345 DV 12" req/><Inp l="Tipo" v={cf.tipo_cliente} ch={v=>uc("tipo_cliente",v)} opts={["B2B","B2C"]}/><Inp l="Contacto" v={cf.contacto_principal} ch={v=>uc("contacto_principal",v)} ph="Nombre"/><Inp l="Teléfono" v={cf.telefono_whatsapp} ch={v=>uc("telefono_whatsapp",v)} ph="+507 6XXX-XXXX"/><Inp l="Email" v={cf.email_facturacion} ch={v=>uc("email_facturacion",v)} type="email" ph="correo@empresa.com"/><Inp l="Prospectado por" v={cf.prospectado_por} ch={v=>uc("prospectado_por",v)} opts={["","...seleccionar",...TEAM]}/><Inp l="Seguimiento por" v={cf.seguimiento_por} ch={v=>uc("seguimiento_por",v)} opts={["","...seleccionar",...TEAM]}/></div></div>}
      <div className="border-t border-slate-200 dark:border-slate-700/30 pt-4 mt-2"><h4 className="text-xs font-semibold text-slate-500 mb-3">Datos del Proyecto</h4><div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><div className="sm:col-span-2"><Inp l="Nombre del Proyecto" v={pf.nombre_proyecto} ch={v=>up("nombre_proyecto",v)} ph="Ej: Construcción Torre Norte" req/></div><Inp l="Presupuesto Aprobado" v={pf.presupuesto_aprobado} ch={v=>up("presupuesto_aprobado",v)} type="number" ph="0.00"/><Inp l="Fecha Inicio" v={pf.fecha_inicio} ch={v=>up("fecha_inicio",v)} type="date"/><Inp l="Project Manager" v={pf.project_manager} ch={v=>up("project_manager",v)} ph="Nombre del PM"/><div className="flex items-end"><div className="w-full p-3 rounded-xl bg-violet-500/10 border border-violet-500/15 text-center"><div className="text-[10px] text-slate-400 uppercase">Estado</div><div className="text-sm font-bold text-violet-600 dark:text-violet-400">Cotizando</div></div></div></div></div>
      <div className="flex justify-end gap-3 mt-6 pt-4 border-t border-slate-200 dark:border-slate-700/30"><button onClick={()=>{sSf(false);sNc(false);}} className="px-4 py-2.5 rounded-xl text-sm text-slate-500">Cancelar</button><button onClick={savePrj} className="flex items-center gap-2 px-5 py-2.5 rounded-xl bg-[#c4a265] hover:bg-[#b8956a] text-white text-sm font-semibold"><Save size={15}/>Crear Proyecto</button></div>
    </Mod></div>;}

function P3V({pid,setView,cls,crm,setCrm,toast,prjs,facs}){const[t,sT]=useState("f");const p=prjs.find(x=>x.id_proyecto===pid);const cl=p?cls.find(c=>c.id_cliente===p.id_cliente):null;const fs=facs.filter(f=>f.id_proyecto===pid);const bs=crm.filter(b=>b.id_proyecto===pid);const ft=fs.reduce((s,f)=>s+f.monto_facturado,0);
  const[nb,sNb]=useState({tc:"Llamada",fc:new Date().toISOString().slice(0,10),n:"",pp:""});
  const addBit=()=>{if(!nb.n){toast("Agrega una nota","error");return;}setCrm(pr=>[{id_interaccion:`INT-${String(pr.length+1).padStart(3,"0")}`,id_proyecto:pid,id_cliente:"",fecha_contacto:nb.fc,tipo_contacto:nb.tc,notas_acuerdos:nb.n,promesa_pago:nb.pp},...pr]);toast("Interacción registrada");sNb({tc:"Llamada",fc:new Date().toISOString().slice(0,10),n:"",pp:""});};
  if(!p)return null;
  return<div className="space-y-5"><button onClick={()=>setView("proyectos")} className="flex items-center gap-1 text-xs text-[#c4a265]"><ChevronLeft size={14}/>Volver</button><div className="cd p-5"><div className="flex flex-col lg:flex-row lg:items-start justify-between gap-4 mb-5"><div><h1 className="text-xl font-bold text-slate-900 dark:text-white">{p.nombre_proyecto}</h1><div className="text-sm text-slate-500 mt-0.5">{cl?.razon_social_nombre}</div><div className="flex gap-3 mt-2 flex-wrap"><span className={`text-[10px] px-2.5 py-1 rounded-full font-semibold ${bg(p.estado_obra)}`}>{p.estado_obra}</span><span className="text-xs text-slate-500">PM: {p.project_manager}</span></div></div><div className="text-right"><div className="text-2xl font-bold text-slate-900 dark:text-white">{$(p.presupuesto_aprobado)}</div><div className="text-xs text-slate-500">Presupuesto</div></div></div><div className="grid grid-cols-3 gap-3">{[{l:"Facturado",v:$(ft),c:"text-[#c4a265]"},{l:"Pagado",v:$(fs.filter(f=>f.estado_cobro==="Pagado").reduce((s,f)=>s+f.monto_facturado,0)),c:"text-emerald-500"},{l:"Por cobrar",v:$(fs.filter(f=>f.estado_cobro!=="Pagado").reduce((s,f)=>s+f.monto_facturado,0)),c:"text-amber-500"}].map(m=><div key={m.l} className="bg-slate-50 dark:bg-slate-900/40 rounded-xl p-3 border border-slate-100 dark:border-slate-700/15"><div className="text-[10px] text-slate-400 uppercase">{m.l}</div><div className={`text-lg font-bold ${m.c}`}>{m.v}</div></div>)}</div></div>
    <div className="flex gap-1 bg-slate-100 dark:bg-slate-800/40 rounded-xl p-1 border border-slate-200 dark:border-slate-700/30 w-fit">{[{i:"f",l:"Facturas",n:fs.length},{i:"b",l:"Bitácora",n:bs.length}].map(x=><button key={x.i} onClick={()=>sT(x.i)} className={`px-4 py-2 rounded-lg text-xs font-semibold ${t===x.i?"bg-white dark:bg-slate-700 shadow-sm text-[#c4a265]":"text-slate-500"}`}>{x.l} ({x.n})</button>)}</div>
    {t==="f"&&<div className="cd overflow-hidden">{fs.length===0?<div className="p-12 text-center text-slate-400">Sin facturas</div>:<div className="overflow-x-auto"><table className="w-full text-left"><thead><tr className="border-b border-slate-200 dark:border-slate-700/30">{["Factura","Concepto","Monto","Venc.","Estado","Mora"].map(h=><th key={h} className="px-4 py-3 text-[10px] font-semibold uppercase text-slate-400">{h}</th>)}</tr></thead><tbody>{fs.map(f=><tr key={f.id_factura} className="border-b border-slate-100 dark:border-slate-700/15"><td className="px-4 py-3 text-xs font-mono text-[#c4a265]">{f.id_factura}</td><td className="px-4 py-3 text-xs text-slate-500 max-w-[180px] truncate">{f.hitos_concepto}</td><td className="px-4 py-3 text-sm font-bold text-slate-900 dark:text-white">{$(f.monto_facturado)}</td><td className="px-4 py-3 text-xs text-slate-500">{fd(f.fecha_vencimiento)}</td><td className="px-4 py-3"><span className={`text-[10px] px-2 py-1 rounded-full font-semibold ${bg(f.estado_cobro)}`}>{f.estado_cobro}</span></td><td className="px-4 py-3 text-xs font-bold">{f.dias_mora>0?<span className="text-red-500">{f.dias_mora}d</span>:"—"}</td></tr>)}</tbody></table></div>}</div>}
    {t==="b"&&<div className="space-y-4">
      <div className="cd p-4 border-dashed border-[#c4a265]/30 bg-[#c4a265]/5 dark:bg-[#c4a265]/5"><h4 className="text-xs font-semibold text-[#c4a265] mb-3 flex items-center gap-1.5"><Plus size={13}/>Nueva entrada de bitácora</h4><div className="grid grid-cols-1 sm:grid-cols-3 gap-3"><Inp l="Tipo" v={nb.tc} ch={v=>sNb(q=>({...q,tc:v}))} opts={["Llamada","Email","Visita a Obra","WhatsApp"]}/><Inp l="Fecha" v={nb.fc} ch={v=>sNb(q=>({...q,fc:v}))} type="date"/><Inp l="Promesa Pago" v={nb.pp} ch={v=>sNb(q=>({...q,pp:v}))} type="date"/></div><div className="mt-3"><Inp l="Notas / Acuerdos" v={nb.n} ch={v=>sNb(q=>({...q,n:v}))} ta ph="Describe la interacción, acuerdos o hallazgos..." req/></div><div className="flex justify-end mt-3"><button onClick={addBit} className="flex items-center gap-2 px-4 py-2 rounded-xl bg-[#c4a265] hover:bg-[#b8956a] text-white text-sm font-semibold"><Save size={14}/>Registrar</button></div></div>
      <div className="cd p-5">{bs.length===0?<div className="text-center py-12 text-slate-400">Sin bitácora</div>:<div className="space-y-2">{[...bs].sort((a,b)=>b.fecha_contacto.localeCompare(a.fecha_contacto)).map(b=>{const I=iM[b.tipo_contacto]||Info;return<div key={b.id_interaccion} className="flex gap-3 p-3 rounded-xl bg-slate-50 dark:bg-slate-900/30 border border-slate-100 dark:border-slate-700/15"><div className="w-9 h-9 rounded-lg bg-[#c4a265]/10 flex items-center justify-center shrink-0"><I size={15} className="text-[#c4a265]"/></div><div><div className="flex items-center gap-2"><span className="text-xs font-semibold text-slate-700 dark:text-slate-200">{b.tipo_contacto}</span><span className="text-[11px] text-slate-500">{fd(b.fecha_contacto)}</span></div><p className="text-xs text-slate-500 mt-0.5">{b.notas_acuerdos}</p>{b.promesa_pago&&<div className="mt-1 text-[10px] px-2 py-0.5 rounded-full bg-amber-500/10 text-amber-600 dark:text-amber-400 border border-amber-500/15 inline-flex items-center gap-1"><Calendar size={9}/>{fd(b.promesa_pago)}</div>}</div></div>;})}</div>}</div>
    </div>}</div>;}

function CoV({cls,prjs,facs,setFacs,toast}){const[fl,sFl]=useState("Todas");const[ef,sEf]=useState(null);const[imp,sImp]=useState(false);const[impData,sImpData]=useState(null);const[impErr,sImpErr]=useState([]);const[impOk,sImpOk]=useState(false);const fileRef=useRef(null);
  const d=fl==="Todas"?facs:fl==="Disputa"?facs.filter(f=>f.estado_cobro==="En Disputa Técnica"):facs.filter(f=>f.estado_cobro===fl);
  // Edit factura
  const ue=(k,v)=>sEf(p=>({...p,[k]:v}));
  const saveF=()=>{if(!ef)return;setFacs(p=>p.map(f=>f.id_factura===ef.id_factura?{...ef,monto_facturado:Number(ef.monto_facturado),dias_mora:Number(ef.dias_mora)}:f));toast("Factura actualizada");sEf(null);};
  // CSV/Excel import
  const COLS=["id_factura","id_proyecto","hitos_concepto","monto_facturado","fecha_vencimiento","dias_mora","estado_cobro"];
  const ESTADOS_V=["Pagado","Pendiente","En Disputa Técnica","Pago Parcial"];
  const parseCSV=(text)=>{const lines=text.trim().split("\n").map(l=>l.split(",").map(c=>c.trim().replace(/^"|"$/g,"")));return{headers:lines[0],rows:lines.slice(1)};};
  const validateData=(headers,rows)=>{
    const errs=[];const missing=COLS.filter(c=>!headers.includes(c));
    if(missing.length>0){errs.push(`Columnas faltantes: ${missing.join(", ")}`);return{errs,valid:[]};}
    const ci=COLS.map(c=>headers.indexOf(c));const valid=[];
    rows.forEach((r,i)=>{
      if(r.length<headers.length){errs.push(`Fila ${i+2}: número de columnas incorrecto`);return;}
      const o={};COLS.forEach((c,j)=>o[c]=r[ci[j]]);
      if(!o.id_factura)errs.push(`Fila ${i+2}: id_factura vacío`);
      if(!o.id_proyecto)errs.push(`Fila ${i+2}: id_proyecto vacío`);
      if(isNaN(Number(o.monto_facturado))||Number(o.monto_facturado)<0)errs.push(`Fila ${i+2}: monto_facturado inválido "${o.monto_facturado}"`);
      if(isNaN(Number(o.dias_mora)))errs.push(`Fila ${i+2}: dias_mora inválido`);
      if(!ESTADOS_V.includes(o.estado_cobro))errs.push(`Fila ${i+2}: estado_cobro inválido "${o.estado_cobro}" (usar: ${ESTADOS_V.join(", ")})`);
      if(!/^\d{4}-\d{2}-\d{2}$/.test(o.fecha_vencimiento))errs.push(`Fila ${i+2}: fecha_vencimiento formato inválido "${o.fecha_vencimiento}" (usar YYYY-MM-DD)`);
      if(errs.length<=8)valid.push({...o,monto_facturado:Number(o.monto_facturado),dias_mora:Number(o.dias_mora)});
    });
    return{errs,valid};
  };
  const onFile=(e)=>{
    const file=e.target.files?.[0];if(!file)return;sImpErr([]);sImpData(null);sImpOk(false);
    const ext=file.name.split(".").pop().toLowerCase();
    if(!["csv","xlsx","xls"].includes(ext)){sImpErr(["Formato no soportado. Usa .csv, .xlsx o .xls"]);return;}
    const reader=new FileReader();
    reader.onload=(ev)=>{
      try{
        let headers,rows;
        if(ext==="csv"){const r=parseCSV(ev.target.result);headers=r.headers;rows=r.rows;}
        else{
          /* For xlsx we use Papaparse-style: read as CSV from the raw text */
          const r=parseCSV(ev.target.result);headers=r.headers;rows=r.rows;
        }
        const{errs,valid}=validateData(headers,rows);
        sImpErr(errs);if(errs.length===0&&valid.length>0){sImpData(valid);sImpOk(true);}
      }catch(err){sImpErr([`Error al procesar: ${err.message}`]);}
    };
    reader.readAsText(file);
    if(fileRef.current)fileRef.current.value="";
  };
  const confirmImport=()=>{if(!impData)return;setFacs(p=>{const ids=new Set(impData.map(f=>f.id_factura));const kept=p.filter(f=>!ids.has(f.id_factura));return[...kept,...impData];});toast(`${impData.length} facturas importadas`);sImpData(null);sImpOk(false);sImpErr([]);sImp(false);};

  return<div className="space-y-5"><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3"><div><h1 className="text-xl lg:text-2xl font-bold text-slate-900 dark:text-white">Cartera</h1><p className="text-sm text-slate-500">{facs.length} facturas</p></div><button onClick={()=>{sImp(true);sImpErr([]);sImpData(null);sImpOk(false);}} className="flex items-center gap-2 px-4 py-2.5 rounded-xl bg-[#c4a265]/10 text-[#c4a265] border border-[#c4a265]/20 text-sm font-semibold"><Upload size={16}/>Importar</button></div>
    <div className="flex gap-1.5 flex-wrap">{["Todas","Pendiente","Pagado","Pago Parcial","Disputa"].map(f=><button key={f} onClick={()=>sFl(f)} className={`px-3 py-2 rounded-xl text-xs font-semibold ${fl===f?"bg-[#c4a265]/10 text-[#c4a265] border border-[#c4a265]/20":"bg-white dark:bg-slate-800/40 text-slate-500 border border-slate-200 dark:border-slate-700/30"}`}>{f}</button>)}</div>
    <div className="lg:hidden space-y-2">{d.map(f=>{const pr=prjs.find(p=>p.id_proyecto===f.id_proyecto);const cl=pr?cls.find(c=>c.id_cliente===pr.id_cliente):null;return<div key={f.id_factura} className="cd p-4" onClick={()=>sEf({...f})}><div className="flex items-start justify-between mb-1"><div><span className="text-xs font-mono text-[#c4a265]">{f.id_factura}</span><div className="text-sm font-bold text-slate-900 dark:text-white mt-0.5">{$(f.monto_facturado)}</div></div><span className={`text-[9px] px-2 py-0.5 rounded-full font-semibold ${bg(f.estado_cobro)}`}>{f.estado_cobro}</span></div><div className="text-xs text-slate-500 truncate">{f.hitos_concepto}</div>{cl&&<div className="text-[11px] text-slate-400">{cl.razon_social_nombre}</div>}{f.dias_mora>0&&<div className="text-[11px] text-red-500 font-semibold mt-1">{f.dias_mora}d mora</div>}</div>;})}</div>
    <div className="hidden lg:block cd overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-left"><thead><tr className="border-b border-slate-200 dark:border-slate-700/30">{["Factura","Proyecto","Cliente","Concepto","Monto","Venc.","Estado","Mora",""].map(h=><th key={h} className="px-4 py-3 text-[10px] font-semibold uppercase text-slate-400">{h}</th>)}</tr></thead><tbody>{d.map(f=>{const pr=prjs.find(p=>p.id_proyecto===f.id_proyecto);const cl=pr?cls.find(c=>c.id_cliente===pr.id_cliente):null;return<tr key={f.id_factura} className="border-b border-slate-100 dark:border-slate-700/15 hover:bg-slate-50 dark:hover:bg-slate-800/40"><td className="px-4 py-3 text-xs font-mono text-[#c4a265]">{f.id_factura}</td><td className="px-4 py-3 text-xs text-slate-600 dark:text-slate-300">{pr?.nombre_proyecto||"—"}</td><td className="px-4 py-3 text-xs text-slate-500">{cl?.razon_social_nombre||"—"}</td><td className="px-4 py-3 text-xs text-slate-500 max-w-[150px] truncate">{f.hitos_concepto}</td><td className="px-4 py-3 text-sm font-bold text-slate-900 dark:text-white">{$(f.monto_facturado)}</td><td className="px-4 py-3 text-xs text-slate-500">{fd(f.fecha_vencimiento)}</td><td className="px-4 py-3"><span className={`text-[10px] px-2 py-1 rounded-full font-semibold ${bg(f.estado_cobro)}`}>{f.estado_cobro}</span></td><td className="px-4 py-3 text-xs font-bold">{f.dias_mora>0?<span className="text-red-500">{f.dias_mora}d</span>:"—"}</td><td className="px-4 py-2"><button onClick={()=>sEf({...f})} className="p-1.5 rounded-lg hover:bg-slate-100 dark:hover:bg-slate-700 text-slate-400 hover:text-[#c4a265]"><Pencil size={13}/></button></td></tr>;})}</tbody></table></div></div>
    {/* EDIT FACTURA MODAL */}
    <Mod open={!!ef} close={()=>sEf(null)} title={`Editar ${ef?.id_factura||""}`} w>{ef&&<><div className="mb-3 p-3 rounded-xl bg-slate-50 dark:bg-slate-800/60 border border-slate-200 dark:border-slate-700/20"><div className="text-[10px] text-slate-400 uppercase">Factura</div><div className="text-sm font-bold text-[#c4a265]">{ef.id_factura}</div><div className="text-xs text-slate-500">{prjs.find(p=>p.id_proyecto===ef.id_proyecto)?.nombre_proyecto}</div></div><div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><Inp l="Proyecto" v={ef.id_proyecto} ch={v=>ue("id_proyecto",v)} opts={prjs.map(p=>({v:p.id_proyecto,l:`${p.id_proyecto} — ${p.nombre_proyecto}`}))}/><Inp l="Concepto / Hito" v={ef.hitos_concepto} ch={v=>ue("hitos_concepto",v)} ph="Descripción"/><Inp l="Monto Facturado" v={ef.monto_facturado} ch={v=>ue("monto_facturado",v)} type="number"/><Inp l="Fecha Vencimiento" v={ef.fecha_vencimiento} ch={v=>ue("fecha_vencimiento",v)} type="date"/><Inp l="Días Mora" v={ef.dias_mora} ch={v=>ue("dias_mora",v)} type="number"/><Inp l="Estado de Cobro" v={ef.estado_cobro} ch={v=>ue("estado_cobro",v)} opts={["Pagado","Pendiente","En Disputa Técnica","Pago Parcial"]}/></div><div className="flex justify-end gap-3 mt-6 pt-4 border-t border-slate-200 dark:border-slate-700/30"><button onClick={()=>sEf(null)} className="px-4 py-2.5 rounded-xl text-sm text-slate-500">Cancelar</button><button onClick={saveF} className="flex items-center gap-2 px-5 py-2.5 rounded-xl bg-[#c4a265] hover:bg-[#b8956a] text-white text-sm font-semibold"><Save size={15}/>Guardar</button></div></>}</Mod>
    {/* IMPORT MODAL */}
    <Mod open={imp} close={()=>sImp(false)} title="Importar Facturas">
      <div className="space-y-4">
        <div className="text-center p-6 rounded-xl border-2 border-dashed border-slate-300 dark:border-slate-600 hover:border-[#c4a265]/40 transition-colors cursor-pointer" onClick={()=>fileRef.current?.click()}>
          <FileSpreadsheet size={36} className="mx-auto mb-3 text-[#c4a265] opacity-70"/>
          <div className="text-sm font-semibold text-slate-700 dark:text-slate-200">Arrastra o haz clic para seleccionar</div>
          <div className="text-xs text-slate-400 mt-1">CSV (.csv) — Máx. columnas requeridas:</div>
          <div className="flex flex-wrap gap-1 justify-center mt-2">{COLS.map(c=><span key={c} className="text-[9px] px-1.5 py-0.5 rounded bg-slate-100 dark:bg-slate-700/60 text-slate-500 font-mono">{c}</span>)}</div>
          <input ref={fileRef} type="file" accept=".csv,.xlsx,.xls" className="hidden" onChange={onFile}/>
        </div>
        <div className="p-3 rounded-xl bg-sky-50 dark:bg-sky-900/20 border border-sky-200 dark:border-sky-500/20"><div className="flex items-start gap-2"><Info size={14} className="text-sky-500 shrink-0 mt-0.5"/><div className="text-xs text-sky-700 dark:text-sky-300"><span className="font-semibold">Formato requerido:</span> El archivo debe tener estas columnas exactas: <span className="font-mono">id_factura, id_proyecto, hitos_concepto, monto_facturado, fecha_vencimiento, dias_mora, estado_cobro</span>. Fechas en formato YYYY-MM-DD. Estados válidos: Pagado, Pendiente, En Disputa Técnica, Pago Parcial.</div></div></div>
        {impErr.length>0&&<div className="p-3 rounded-xl bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-500/20"><div className="flex items-start gap-2"><ShieldAlert size={14} className="text-red-500 shrink-0 mt-0.5"/><div><div className="text-xs font-semibold text-red-700 dark:text-red-300 mb-1">Errores de validación ({impErr.length})</div><div className="space-y-0.5 max-h-[120px] overflow-y-auto">{impErr.map((e,i)=><div key={i} className="text-[11px] text-red-600 dark:text-red-400">{e}</div>)}</div></div></div></div>}
        {impOk&&impData&&<div className="p-3 rounded-xl bg-emerald-50 dark:bg-emerald-900/20 border border-emerald-200 dark:border-emerald-500/20"><div className="flex items-center gap-2"><CheckCircle size={14} className="text-emerald-500"/><div className="text-xs text-emerald-700 dark:text-emerald-300"><span className="font-semibold">{impData.length} facturas válidas</span> listas para importar. Las facturas con ID existente serán actualizadas.</div></div></div>}
        <div className="flex justify-end gap-3 pt-2">{impOk&&impData&&<button onClick={confirmImport} className="flex items-center gap-2 px-5 py-2.5 rounded-xl bg-emerald-500 hover:bg-emerald-400 text-white text-sm font-semibold"><Upload size={15}/>Importar {impData.length} facturas</button>}</div>
      </div>
    </Mod></div>;}

function BiV({crm,setCrm,cls,toast,prjs}){const[sf,sSf]=useState(false);const[ft,sFt]=useState("Todos");const em={lt:"proyecto",pi:prjs[0]?.id_proyecto||"",ci:"",fc:new Date().toISOString().slice(0,10),tc:"Llamada",n:"",pp:""};const[fm,sFm]=useState(em);const u=(k,v)=>sFm(p=>({...p,[k]:v}));
  useEffect(()=>{if(fm.lt==="proyecto"&&!fm.pi&&prjs[0]?.id_proyecto)sFm(p=>({...p,pi:prjs[0].id_proyecto}));},[fm.lt,fm.pi,prjs]);
  const sv=async()=>{if(!fm.n?.trim()){toast("Agrega una nota","error");return;}if(fm.lt==="proyecto"&&!fm.pi){toast("Selecciona un proyecto","error");return;}if(fm.lt==="cliente"&&!fm.ci){toast("Selecciona un cliente","error");return;}try{const payload={id_interaccion:`INT-${String(crm.length+1).padStart(3,"0")}`,id_proyecto:fm.lt==="proyecto"?fm.pi:"",id_cliente:fm.lt==="cliente"?fm.ci:"",fecha_contacto:fm.fc,tipo_contacto:fm.tc,notas_acuerdos:fm.n.trim(),promesa_pago:fm.pp||""};await googleSheetsService.createRegistro("CRM",payload);setCrm(p=>[payload,...p]);toast("Interacción registrada");sFm({ ...em, pi: prjs[0]?.id_proyecto||"" });sSf(false);}catch(error){console.error("Error guardando interacción CRM:",error);toast("No se pudo guardar la interacción CRM","error");}};
  const so=[...crm].sort((a,b)=>b.fecha_contacto.localeCompare(a.fecha_contacto));const fi=ft==="Todos"?so:ft==="Proyectos"?so.filter(b=>b.id_proyecto):so.filter(b=>b.id_cliente&&!b.id_proyecto);
  const ppj=fm.lt==="proyecto"?prjs.find(p=>p.id_proyecto===fm.pi):null;const ppc=fm.lt==="cliente"?cls.find(c=>c.id_cliente===fm.ci):null;
  return<div className="space-y-5"><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3"><div><h1 className="text-xl lg:text-2xl font-bold text-slate-900 dark:text-white">Bitácora CRM</h1><p className="text-sm text-slate-500">{crm.length} interacciones</p></div><button onClick={()=>sSf(true)} className="flex items-center gap-2 px-4 py-2.5 rounded-xl bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border border-emerald-500/20 text-sm font-semibold"><Plus size={16}/>Nueva</button></div>
    <div className="flex gap-1.5">{["Todos","Proyectos","Clientes"].map(f=><button key={f} onClick={()=>sFt(f)} className={`px-3 py-2 rounded-xl text-xs font-semibold flex items-center gap-1.5 ${ft===f?"bg-[#c4a265]/10 text-[#c4a265] border border-[#c4a265]/20":"bg-white dark:bg-slate-800/40 text-slate-500 border border-slate-200 dark:border-slate-700/30"}`}>{f==="Proyectos"&&<FolderKanban size={12}/>}{f==="Clientes"&&<User size={12}/>}{f}</button>)}</div>
    <div className="space-y-3">{fi.map(b=>{const I=iM[b.tipo_contacto]||Info;const pr=gP(b,prjs);const cl=gC(b,cls,prjs);const co=!b.id_proyecto&&b.id_cliente;return<div key={b.id_interaccion} className="cd p-4"><div className="flex items-start gap-3"><div className="w-10 h-10 rounded-xl bg-[#c4a265]/10 flex items-center justify-center shrink-0"><I size={16} className="text-[#c4a265]"/></div><div className="flex-1 min-w-0"><div className="flex items-center gap-2 flex-wrap mb-1"><span className="text-sm font-semibold text-slate-800 dark:text-white">{b.tipo_contacto}</span><span className="text-[11px] text-slate-400">{fd(b.fecha_contacto)}</span>{co?<span className="text-[10px] px-2 py-0.5 rounded-md bg-violet-500/10 text-violet-500 border border-violet-500/15 inline-flex items-center gap-1"><User size={9}/>Cliente</span>:<span className="text-[10px] px-2 py-0.5 rounded-md bg-[#c4a265]/10 text-[#c4a265] border border-[#c4a265]/15 inline-flex items-center gap-1"><FolderKanban size={9}/>Proyecto</span>}</div>{pr&&<div className="text-[11px] text-[#c4a265]/70 mb-0.5">{pr.nombre_proyecto}</div>}{cl&&<div className="text-[11px] text-slate-500 mb-1">{cl.razon_social_nombre}</div>}<p className="text-sm text-slate-700 dark:text-slate-300">{b.notas_acuerdos}</p>{b.promesa_pago&&<div className="mt-2 text-[11px] px-3 py-1.5 rounded-xl bg-amber-500/10 text-amber-600 dark:text-amber-300 border border-amber-500/15 inline-flex items-center gap-1.5"><Calendar size={11}/>Promesa: {fd(b.promesa_pago)}</div>}</div></div></div>;})}</div>
    <Mod open={sf} close={()=>sSf(false)} title="Nueva Interacción CRM" w>
      <div className="mb-5"><label className="block text-xs font-semibold text-slate-500 mb-2">Vincular a:</label><div className="flex gap-2"><button onClick={()=>u("lt","proyecto")} className={`flex-1 flex items-center justify-center gap-2 p-3 rounded-xl border text-sm font-semibold ${fm.lt==="proyecto"?"bg-[#c4a265]/10 text-[#c4a265] border-[#c4a265]/30":"bg-slate-50 dark:bg-slate-800/40 text-slate-500 border-slate-200 dark:border-slate-700/30"}`}><FolderKanban size={16}/>Proyecto</button><button onClick={()=>u("lt","cliente")} className={`flex-1 flex items-center justify-center gap-2 p-3 rounded-xl border text-sm font-semibold ${fm.lt==="cliente"?"bg-violet-500/10 text-violet-600 dark:text-violet-400 border-violet-500/30":"bg-slate-50 dark:bg-slate-800/40 text-slate-500 border-slate-200 dark:border-slate-700/30"}`}><User size={16}/>Cliente</button></div><p className="text-[11px] text-slate-400 mt-1.5">{fm.lt==="cliente"?"Para prospectos o cotizaciones sin proyecto.":"Vincula a proyecto existente."}</p></div>
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">{fm.lt==="proyecto"?<Inp l="Proyecto" v={fm.pi} ch={v=>u("pi",v)} opts={prjs.map(p=>({v:p.id_proyecto,l:`${p.id_proyecto} — ${p.nombre_proyecto}`}))}/>:<Inp l="Cliente" v={fm.ci} ch={v=>u("ci",v)} opts={cls.map(c=>({v:c.id_cliente,l:`${c.id_cliente} — ${c.razon_social_nombre}`}))}/>}<Inp l="Tipo" v={fm.tc} ch={v=>u("tc",v)} opts={["Llamada","Email","Visita a Obra","WhatsApp"]}/><Inp l="Fecha" v={fm.fc} ch={v=>u("fc",v)} type="date"/><Inp l="Promesa Pago" v={fm.pp} ch={v=>u("pp",v)} type="date"/><div className="sm:col-span-2"><Inp l="Notas / Acuerdos" v={fm.n} ch={v=>u("n",v)} ta ph="Describe la interacción..." req/></div></div>
      {(ppj||ppc)&&<div className="mt-4 p-3 rounded-xl bg-slate-50 dark:bg-slate-800/50 border border-slate-200 dark:border-slate-700/30"><div className="text-[10px] uppercase tracking-wide text-slate-400 mb-1">Vista previa</div>{ppj&&<div className="text-sm text-slate-700 dark:text-slate-200"><span className="font-semibold">Proyecto:</span> {ppj.nombre_proyecto}</div>}{ppc&&<div className="text-sm text-slate-700 dark:text-slate-200"><span className="font-semibold">Cliente:</span> {ppc.razon_social_nombre}</div>}</div>}
      <div className="flex justify-end gap-3 mt-6 pt-4 border-t border-slate-200 dark:border-slate-700/30"><button onClick={()=>sSf(false)} className="px-4 py-2.5 rounded-xl text-sm text-slate-500">Cancelar</button><button onClick={sv} className="flex items-center gap-2 px-5 py-2.5 rounded-xl bg-[#c4a265] hover:bg-[#b8956a] text-white text-sm font-semibold"><Save size={15}/>Registrar</button></div>
    </Mod></div>;}

function App(){
  const[role,sR]=useState(null);const[col,sCol]=useState(false);const[mob,sMob]=useState(false);const[view,sV]=useState(null);const[sp,sSP]=useState(null);const[selC,sSelC]=useState(null);const[dark,sD]=useState(true);const[vm,sVm]=useState("desktop");const[ts,sTs]=useState([]);
  
  // 1. Estados inicializados vacíos y agregamos el estado de carga
  const[cls,sCls]=useState([]);
  const[crm,sCrm]=useState([]);
  const[prjs,sPrjs]=useState([]);
  const[facs,sFacs]=useState([]);
  const[tasks,sTasks]=useState([]);
  const[loading,setLoading]=useState(true);

  useEffect(()=>{const w=window.innerWidth;if(w<640)sVm("mobile");else if(w<1024)sVm("tablet");},[]);
  useEffect(()=>{if(!role)return;sV(role==="cobros"?"dash-cobros":"dash-crm");},[role]);

  // 2. Disparamos la carga desde Google Sheets al abrir la app
  useEffect(() => {
    const fetchDatos = async () => {
      try {
        const data = await googleSheetsService.loadAll();
        if (data) {
          sCls(data.clientes || []);
          sPrjs(data.proyectos || []);
          sFacs(data.cuentas || []); 
          sCrm(data.crm || []);
          sTasks(data.tareas || []);
        }
      } catch (error) {
        console.error("Fallo la carga inicial", error);
      } finally {
        setLoading(false);
      }
    };
    fetchDatos();
  }, []);

  const toast=(m,y="success")=>{const id=Date.now();sTs(p=>[...p,{id,m,y}]);setTimeout(()=>sTs(p=>p.filter(t=>t.id!==id)),4000);};
  const vw={mobile:"max-w-[430px]",tablet:"max-w-[820px]",desktop:"max-w-none"}[vm];
  const rv=()=>{switch(view){case"dash-crm":return<DashCRM cls={cls} crm={crm} prjs={prjs}/>;case"dash-cobros":return<DashCob cls={cls} prjs={prjs} facs={facs}/>;case"clientes":return<ClV cls={cls} setCls={sCls} toast={toast} crm={crm} setCrm={sCrm} prjs={prjs} setView={sV} setSelC={sSelC} facs={facs}/>;case"c360":return<C3V cid={selC} setView={sV} cls={cls} setCls={sCls} crm={crm} setCrm={sCrm} prjs={prjs} toast={toast} facs={facs}/>;case"proyectos":return<PrV cls={cls} setCls={sCls} setView={sV} setSP={sSP} prjs={prjs} setPrjs={sPrjs} toast={toast} facs={facs}/>;case"p360":return<P3V pid={sp} setView={sV} cls={cls} crm={crm} setCrm={sCrm} toast={toast} prjs={prjs} facs={facs}/>;case"cobros":return<CoV cls={cls} prjs={prjs} facs={facs} setFacs={sFacs} toast={toast}/>;case"tareas":return<TarV tasks={tasks} setTasks={sTasks} prjs={prjs} toast={toast}/>;case"bitacora":return<BiV crm={crm} setCrm={sCrm} cls={cls} toast={toast} prjs={prjs}/>;default:return<DashCRM cls={cls} crm={crm} prjs={prjs}/>;}};

  // 3. Mostramos una pantalla de carga mientras Netlify se comunica con Google Sheets
  if(loading) return <div className="min-h-screen flex items-center justify-center bg-[#f8f6f1] dark:bg-[#0b1120]"><div className="text-[#c4a265] font-bold text-lg animate-pulse flex flex-col items-center gap-3"><div className="w-10 h-10 border-4 border-[#c4a265] border-t-transparent rounded-full animate-spin"></div>Conectando con la Base de Datos...</div></div>;

  if(!role)return<ThemeCtx.Provider value={{dark,toggle:()=>sD(d=>!d)}}><div className={dark?"dark":""}><style>{CSS}</style><RoleSel setRole={sR}/></div></ThemeCtx.Provider>;
  return<ThemeCtx.Provider value={{dark,toggle:()=>sD(d=>!d)}}><div className={dark?"dark":""}><style>{CSS}</style><div className="min-h-screen bg-[#f5f3ee] dark:bg-[#0b1120] transition-colors duration-300"><Sidebar col={col} setCol={sCol} view={view} setView={sV} mob={mob} setMob={sMob} role={role}/><Topbar setMob={sMob} role={role} setRole={sR} vm={vm} setVm={sVm}/><main className={`pt-14 transition-all duration-300 ${col?"lg:pl-[68px]":"lg:pl-[230px]"}`}><div className={`mx-auto p-4 lg:p-6 transition-all duration-300 ${vw}`}>{rv()}</div></main><Toast ts={ts} rm={id=>sTs(p=>p.filter(t=>t.id!==id))}/></div></div></ThemeCtx.Provider>;
}

const CSS=`@import url('https://fonts.googleapis.com/css2?family=DM+Sans:opsz,wght@9..40,400;9..40,500;9..40,600;9..40,700&display=swap');*{font-family:'DM Sans',system-ui,sans-serif;box-sizing:border-box}body{margin:0;-webkit-font-smoothing:antialiased}:root{--tt-bg:#fff;--tt-border:#e2e8f0;--tt-text:#334155;--grid:#e2e8f0;--ax:#64748b}.dark{--tt-bg:#1e293b;--tt-border:#334155;--tt-text:#e2e8f0;--grid:#1e293b;--ax:#64748b}.cd{border-radius:1rem;border:1px solid #e2e8f0;background:#fff}.dark .cd{border-color:rgba(51,65,85,.4);background:rgba(30,41,59,.3)}@keyframes sU{from{opacity:0;transform:translateY(16px)}to{opacity:1;transform:translateY(0)}}.line-clamp-2{display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}::-webkit-scrollbar{width:6px;height:6px}::-webkit-scrollbar-track{background:transparent}.dark ::-webkit-scrollbar-thumb{background:#334155;border-radius:10px}::-webkit-scrollbar-thumb{background:#cbd5e1;border-radius:10px}`;
export default App;
